# Generated by Django 4.2.16 on 2024-11-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_userpreference_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='eco_friendly',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='family_friendly',
        ),
    ]
