# Generated by Django 4.2.16 on 2024-11-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_userpreference_eco_friendly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_budget_range',
            field=models.CharField(max_length=50),
        ),
    ]
