# Generated by Django 4.2.16 on 2024-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='location',
        ),
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
