# Generated by Django 4.2.16 on 2024-11-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_remove_destinations_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='itinerary',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
