# Generated by Django 4.2.16 on 2024-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_destinations_itinerary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='exclusion',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='destinations',
            name='inclusion',
            field=models.JSONField(default=list),
        ),
    ]
