# Generated by Django 4.2.16 on 2024-12-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_destinations_exclusion_destinations_inclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='destinations',
            name='destination_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
