# Generated by Django 4.2.16 on 2024-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_destinations_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_activities',
            field=models.JSONField(default=list),
        ),
    ]
