# Generated by Django 4.2.16 on 2024-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_alter_userpreference_preferred_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_activities',
            field=models.JSONField(default=list, null=True),
        ),
    ]
