# Generated by Django 4.2.16 on 2024-12-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_alter_destinations_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_activities',
            field=models.JSONField(default=list),
        ),
    ]
