# Generated by Django 4.2.16 on 2024-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_destinations_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_activities',
            field=models.CharField(max_length=255),
        ),
    ]
