# Generated by Django 4.2.16 on 2024-12-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_destinations_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_activities',
        ),
    ]
