# Generated by Django 4.2.16 on 2024-12-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_remove_userpreference_preferred_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='preferred_activities',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
